- name: Install the correct web server for RHEL
  ansible.builtin.command:
    cmd: echo "fsdf"
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Install the correct web server for Debian
  ansible.builtin.command:
    cmd: echo "fdfs"
  when: ansible_facts['os_family']|lower == 'debian'
