# Author: Christian TANKEU
# Pseudo: GhostSecurity
# Email: tankeuchristian1@gmail.com

- name: TEST BOUCLE
  hosts: webservers

  tasks:
    - name: Register loop output as a variable
      ansible.builtin.command:
        cmd: "echo {{ item }}"
      loop:
        - "one"
        - "two"
      register: echo
      changed_when: false
    - name: fdsdfg
      ansible.builtin.fail:
        msg: "La commande ({{ item.cmd }})"
      when: item.rc != 0
      loop: "{{ echo.results }}"
