# Author: Christian TANKEU
# Pseudo: GhostSecurity
# Email: tankeuchristian1@gmail.com

- name: TEST BOUCLE
  hosts: webservers
  become: true

  tasks:
    - name: Register loop output as a variable
      ansible.builtin.shell: "echo {{ item }}"
      loop:
        - "one"
        - "two"
      register: echo
