# Author: Christian TANKEU
# Pseudo: GhostSecurity
# Email: tankeuchristian1@gmail.com

- name: TEST BOUCLE
  hosts: webservers

  tasks:
    - name: Copier ficher de host vers web01
      ansible.builtin.command:
        cmd: rsync -a playbook.yaml {{ inventory_hostname }}:~/
      changed_when: false
      delegate_to: 127.0.0.1
