# Author: Christian TANKEU
# Pseudo: GhostSecurity
# Email: tankeuchristian1@gmail.com

- name: TEST BOUCLE
  hosts: webservers

  tasks:
    - name: Lister les fichers
      ansible.builtin.command:
        cmd: ls -l
      when:
        - ansible_facts['os_family'] == "Debian"
        - ansible_facts['lsb']['major_release'] == "19"
      register: list
    - name: Afficher les resultats
      ansible.builtin.command:
        cmd: echo "{{ list.stdout.find('chris') }}"
      changed_when: false
    - name: Debug
      ansible.builtin.debug:
        msg: "{{ list.stdout }}"
