# Author: Christian TANKEU
# Pseudo: GhostSecurity
# Email: tankeuchristian1@gmail.com

- name: TEST BOUCLE
  hosts: webservers

  tasks:
    - name: Register loop output as a variable
      ansible.builtin.command:
        cmd: "echo {{ item }}"
      loop:
        - "one"
        - "two"
      register: echo
      changed_when: false
