# Author: Christian TANKEU
# Pseudo: GhostSecurity
# Email: tankeuchristian1@gmail.com

- name: TEST BOUCLE
  hosts: webservers

  tasks:
    - name: Lister les fichers
      ansible.builtin.command:
        cmd: ls -l
      when:
        - ansible_facts['os_family'] == "Debian"
        - ansible_facts['distribution_major_version'] == "6"
